[package]
name = "ranklab-api"
version = "0.1.0"
authors = ["Matteo Depalo <matteo@depalo.me>"]
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json", "serde_json"] }
rusoto_core = "0.46.0"
rusoto_s3 = "0.46.0"
uuid = { version = "0.8.2", features = ["v4"] }
serde = "1.0.126"
diesel = { version = "1.4.7" }

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
features = ["diesel_postgres_pool"]
