[package]
name = "ranklab-api"
version = "0.1.0"
authors = ["Matteo Depalo <matteo@depalo.me>"]
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json", "serde_json", "uuid"] }
rusoto_core = "0.47.0"
rusoto_s3 = "0.46.0"
uuid = { version = "0.8.2", features = ["v4", "serde"] }
serde = "1.0.126"
diesel = { version = "1.4.8", features = ["uuidv07"] }
diesel_migrations = "1.4.0"
regex = "1.5.4"
reqwest = { version = "0.11.6", features = ["json"] }
jsonwebtoken = "8.0.0-beta.5"
thiserror = "1.0.30"
validator = { version = "0.14.0", features = ["derive"] }
rocket_okapi = { git = "https://github.com/GREsau/okapi", features = ["uuid"] }
schemars = "0.8.6"
okapi = { git = "https://github.com/GREsau/okapi", features = ["derive_json_schema"] }
sentry = "0.23.0"

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
features = ["diesel_postgres_pool"]
