[package]
name = "ranklab-api"
version = "0.1.0"
authors = ["Matteo Depalo <matteo@depalo.me>"]
edition = "2018"

[dependencies]
ammonia = "3.2.0"
rocket = { version = "0.5.0-rc.1", features = ["json", "serde_json", "uuid"] }
rusoto_core = "0.48.0"
rusoto_s3 = "0.48.0"
rusoto_credential = "0.48.0"
rusoto_signature = "0.48.0"
rusoto_sqs = "0.48.0"
rusoto_sesv2 = "0.48.0"
uuid = { version = "0.8.2", features = ["v4", "serde"] }
serde = "1.0.137"
serde_json = "1.0.81"
diesel = { version = "1.4.8", features = ["uuidv07"] }
diesel_migrations = "1.4.0"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["json"] }
jsonwebtoken = "8.1.0"
thiserror = "1.0.31"
validator = { version = "0.15.0", features = ["derive"] }
rocket_okapi = { git = "https://github.com/GREsau/okapi", features = ["uuid"] }
schemars = "0.8.10"
okapi = { git = "https://github.com/GREsau/okapi" }
sentry = "0.26.0"
dotenv = "0.15.0"
mime_guess = "2.0.4"
lazy_static = "1.4.0"
diesel_as_jsonb = "0.1.3"
async-stripe = { git = "https://github.com/ranklab-gaming/async-stripe", features = [
  "runtime-tokio-hyper",
  "checkout",
  "connect",
  "webhook-events",
], default_features = false }
anyhow = "1.0.57"
hyper = "0.14.18"
hyper-tls = "0.5.0"
diesel-derive-enum = { version = "1.1.2", features = ["postgres"] }
rocket_sync_db_pools = { version = "0.1.0-rc.1", features = [
  "diesel_postgres_pool",
] }
hmac = "0.12.1"
sha2 = "0.10.2"
hex = "0.4.3"
serde_path_to_error = "0.1.7"
smol_str = "0.1.23"
derive_builder = "0.11.2"

[profile.release]
debug = true
