[package]
name = "ranklab-api"
version = "0.1.0"
authors = ["Matteo Depalo <matteo@depalo.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json", "serde_json"] }
rusoto_core = "0.46.0"
rusoto_s3 = "0.46.0"
uuid = { version = "0.8.2", features = ["v4"] }
serde = "1.0.126"
openssl = { version = "0.10.35", optional = true }

[features]
vendored = ["openssl/vendored"]
