[default]
auth0_issuer_base_url = "https://ranklab-development.eu.auth0.com/"

[test]
auth0_issuer_base_url = "http://ranklab-test:3000/oidc/"

[release]
auth0_issuer_base_url = "https://auth.ranklab.gg/"