[debug.databases.default]
url = "postgres://postgres:postgres@postgres:5432/app"

[test.databases.default]
url = "postgres://postgres:postgres@postgres:5432/app_test"

[release]
log_level = "normal"
address = "0.0.0.0"
