version: "3"
services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - ranklab
    ports:
      - "5432:5432"
  ranklab-api:
    environment:
      - ROCKET_ADDRESS=0.0.0.0
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - ranklab
    depends_on:
      - postgres
volumes:
  postgres:
networks:
  ranklab:
    name: ranklab
