version: "3"
services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  workspace:
    env_file: .env
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - local:/usr/local
      - ../:/workspace
volumes:
  postgres:
  local:
