version: "3"
services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - ranklab
  ranklab-api:
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app
      - ROCKET_ADDRESS=0.0.0.0
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - local:/usr/local
    networks:
      - ranklab
volumes:
  postgres:
  local:
networks:
  ranklab:
    name: ranklab
