name: ci
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
  deploy:
    runs-on: ubuntu-latest
    env:
      APP: ranklab-api-production
    if: github.ref == 'refs/heads/master'
    needs: build_and_test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Docker cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Install pip requirements
        run: pip install -r requirements.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
      - name: Log in to the Github Container registry
        uses: docker/login-action@70e1ff84cbd75a9e03941a79f21f05f1b03a71bb
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to ECR and Github Container Registry
        id: docker-build
        uses: docker/build-push-action@v2
        timeout-minutes: 40
        with:
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: |
            ${{ steps.ecr-login.outputs.registry }}/${{ env.APP }}:latest
            ghcr.io/${{ github.repository }}:latest
      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Set up Dockerrun.aws.json
        run: |
          registry="${{ steps.ecr-login.outputs.registry }}"
          digest="${{ steps.docker-build.outputs.digest }}"
          content=$(jq ".Image.Name = \"${registry}/${{ env.APP }}@${digest}\"" Dockerrun.aws.json)
          echo "${content}" > Dockerrun.aws.json
          git add Dockerrun.aws.json
      - name: Deploy to EB
        run: |
          eb init --region eu-west-2 --platform docker ${{ env.APP }}
          eb deploy --staged ${{ env.APP }}
